// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/trtstm/storesservice/swagger/models"
)

// GetBicycleStoresOKCode is the HTTP code returned for type GetBicycleStoresOK
const GetBicycleStoresOKCode int = 200

/*GetBicycleStoresOK A list of bicycle stores near sergels torg.

swagger:response getBicycleStoresOK
*/
type GetBicycleStoresOK struct {

	/*
	  In: Body
	*/
	Payload []*models.BicycleStore `json:"body,omitempty"`
}

// NewGetBicycleStoresOK creates GetBicycleStoresOK with default headers values
func NewGetBicycleStoresOK() *GetBicycleStoresOK {

	return &GetBicycleStoresOK{}
}

// WithPayload adds the payload to the get bicycle stores o k response
func (o *GetBicycleStoresOK) WithPayload(payload []*models.BicycleStore) *GetBicycleStoresOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bicycle stores o k response
func (o *GetBicycleStoresOK) SetPayload(payload []*models.BicycleStore) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBicycleStoresOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.BicycleStore, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBicycleStoresInternalServerErrorCode is the HTTP code returned for type GetBicycleStoresInternalServerError
const GetBicycleStoresInternalServerErrorCode int = 500

/*GetBicycleStoresInternalServerError Could not process request.

swagger:response getBicycleStoresInternalServerError
*/
type GetBicycleStoresInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetBicycleStoresInternalServerError creates GetBicycleStoresInternalServerError with default headers values
func NewGetBicycleStoresInternalServerError() *GetBicycleStoresInternalServerError {

	return &GetBicycleStoresInternalServerError{}
}

// WithPayload adds the payload to the get bicycle stores internal server error response
func (o *GetBicycleStoresInternalServerError) WithPayload(payload string) *GetBicycleStoresInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get bicycle stores internal server error response
func (o *GetBicycleStoresInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBicycleStoresInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
