// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Bicycle store api",
    "version": "0.0.1"
  },
  "paths": {
    "/bicyclestores": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "getBicycleStores",
        "parameters": [
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A list of bicycle stores near sergels torg.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/BicycleStore"
              }
            }
          },
          "500": {
            "description": "Could not process request.",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BicycleStore": {
      "type": "object",
      "required": [
        "name",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Bicycle store api",
    "version": "0.0.1"
  },
  "paths": {
    "/bicyclestores": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "getBicycleStores",
        "parameters": [
          {
            "type": "string",
            "name": "search",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "A list of bicycle stores near sergels torg.",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/BicycleStore"
              }
            }
          },
          "500": {
            "description": "Could not process request.",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "BicycleStore": {
      "type": "object",
      "required": [
        "name",
        "address"
      ],
      "properties": {
        "address": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}`))
}
